### ISSUE TITLE
Receiving error on Typescript build after upgrading to v5.0.2

### ISSUE THREAD

**Issue by robinbayer** [grid-js/gridjs#1173]
Receiving the following build errors when running tsc against the newly-upgraded source for version 5.0.2:

```
node_modules/gridjs/dist/src/pipeline/pipeline.d.ts:19:39 - error TS2344: Type 'P' does not satisfy the constraint 'Partial<PipelineProcessorProps>'.

19     get steps(): PipelineProcessor<T, P>[];
                                         ~

  node_modules/gridjs/dist/src/pipeline/pipeline.d.ts:10:27
    10 declare class Pipeline<T, P = unknown> extends EventEmitter<PipelineEvents<T>> {
                                 ~~~~~~~~~~~
    This type parameter might need an `extends Partial<PipelineProcessorProps>` constraint.

node_modules/gridjs/dist/src/pipeline/pipeline.d.ts:20:63 - error TS2344: Type 'P' does not satisfy the constraint 'Partial<PipelineProcessorProps>'.

20     getStepsByType(type: ProcessorType): PipelineProcessor<T, P>[];
                                                                 ~

  node_modules/gridjs/dist/src/pipeline/pipeline.d.ts:10:27
    10 declare class Pipeline<T, P = unknown> extends EventEmitter<PipelineEvents<T>> {
                                 ~~~~~~~~~~~
    This type parameter might need an `extends Partial<PipelineProcessorProps>` constraint.

node_modules/gridjs/dist/src/pipeline/processor.d.ts:15:52 - error TS2344: Type 'P' does not satisfy the constraint 'Partial<PipelineProcessorProps>'.

15     propsUpdated: (processor: PipelineProcessor<T, P>) => void;
                                                      ~

  node_modules/gridjs/dist/src/pipeline/processor.d.ts:14:38
    14 interface PipelineProcessorEvents<T, P> {
                                            ~
    This type parameter might need an `extends Partial<PipelineProcessorProps>` constraint.

node_modules/gridjs/dist/src/view/base.d.ts:5:67 - error TS2344: Type 'unknown' does not satisfy the constraint 'BaseProps'.

5 export declare abstract class BaseComponent<P extends BaseProps = unknown, S = unknown> extends Component<P, S> {
                                                                    ~~~~~~~


Found 4 errors in 3 files.

Errors  Files
     2  node_modules/gridjs/dist/src/pipeline/pipeline.d.ts:19
     1  node_modules/gridjs/dist/src/pipeline/processor.d.ts:15
     1  node_modules/gridjs/dist/src/view/base.d.ts:5

```

Typescript is newest version 4.8.4.  OS is macOS Monterrey v12.6.  

tsconfig.json is as follows:

`{
    "compilerOptions": {
      "target": "ESNext",
      "useDefineForClassFields": true,
      "module": "ESNext",
      "lib": ["ESNext", "DOM"],
      "moduleResolution": "Node",
      "strict": true,
      "sourceMap": true,
      "resolveJsonModule": true,
      "esModuleInterop": true,
      "noEmit": false,
      "noUnusedLocals": false,
      "noUnusedParameters": false,
      "noImplicitReturns": true,
      "types": ["leaflet"],
      "outDir": "public/js"    
    },
    "include": ["public"]
  }
  `

**Comment by chrisweight** [comment]
I'm having this issue with TypeScript 5.1.3 and gridjs 6.0.5

**Comment by StephanTLavavej** [comment]
I'm observing the same issue with TypeScript 5.1.6 and gridjs 6.0.5 and 6.0.6. This appears to completely block usage from TypeScript for the simplest Hello Worlds.
